on:
  push:
    branches:
      - prod
name: Deploy to Production
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload via FTP to IONOS
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
            server: ${{ secrets.GST_FTP_HOST }}
            port: 22
            username: ${{ secrets.GST_FTP_USERNAME }}
            password: ${{ secrets.GST_FTP_PASSWORD }}
            local_path: './dist/*'
            remote_path: ${{ secrets.FTP_FOLDER }}
            sftp_only: true
            delete_remote_files: false
